name: Build [Clang] - Windows
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Clang
        run: |
          curl -o .\clang.zip -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20240518/llvm-mingw-20240518-ucrt-x86_64.zip
          Expand-Archive .\clang.zip -DestinationPath .\clang

      - name: Test Clang
        run: |
          dir
          .\clang\bin\clang++ --version
